### ISSUE TITLE
Additional notebooks to consider? 

### ISSUE THREAD

**Issue by LaureZanna** [m2lines/L96_demo#101]
@dhruvbalwada @shan18 @IamShubhamGupto : here are a few more pieces that might be cool to have in our Jupyter Book: 

- [ equation discovery](https://github.com/m2lines/team-meetings/tree/main/22-01-12-deep_vs_other_ML)
- [ResNet](https://github.com/m2lines/team-meetings/tree/main/21-10-06-NN) 
- [constraints](https://github.com/m2lines/team-meetings/blob/main/21-10-20-metrics-for-ML/adding_learning_constraints_final.ipynb)
- [CNN vs. ANN](https://github.com/m2lines/team-meetings/blob/main/21-12-01-CNNvsANN/local_map_L96_and_Burgers.ipynb)
- [GP](https://github.com/m2lines/team-meetings/tree/main/22-05-04-WillC-WillG_Updates)

**Comment by dhruvbalwada** [comment]
@IamShubhamGupto - bring the GP notebook in, and post right after random forest. 
@William-gregory - could you please help us integrate it in with the rest of the books, after Shubham has incorporated it in.

**Comment by dhruvbalwada** [comment]
@IamShubhamGupto - when you get a chance (and if you have time) could you incorporate the CNN vs ANN and Resnet notebooks into our jupyter book. I have introduced a 'catch-all' section in the new PR #134  called Other ML approaches for Lorenz-96, which is where these notebooks can be added.

**Comment by IamShubhamGupto** [comment]
@dhruvbalwada 

I will have this ready by Thursday-friday, focusing on the website for the next 2 days

**Comment by IamShubhamGupto** [comment]
@dhruvbalwada I think we can close this
