### ISSUE TITLE
Missing Jupyterbook title

### ISSUE THREAD

**Issue by LaureZanna** [m2lines/L96_demo#106]
I just noticed that the title of the book disappeared... I believe we had something like "Learning Machine Learning and Climate Modeling with Lorenz 96" or something like that. We can change that but we should definitely have a title.

**Comment by shan18** [comment]
I just pulled the main branch of the repo and am able to see the title as well as the search bar in my local build but the version deployed on the website has both of them missing. It might be something related to the dependencies that are being installed on the remote version.

## How it looks on my local build
![Screenshot 2023-05-02 at 12 03 08 AM](https://user-images.githubusercontent.com/12576178/235576825-fa163504-d1aa-4bf3-b331-0fde42dbe4fa.png)

## How it looks on the website
![Screenshot 2023-05-02 at 12 06 13 AM](https://user-images.githubusercontent.com/12576178/235577139-d10272d4-1077-4995-9c3c-fadf40be6be5.png)

**Comment by IamShubhamGupto** [comment]
Hey @LaureZanna @dhruvbalwada 

I was playing around with the configuration from the latest commit and these are my findings:
- I deleted the entire `_build` directory and re compiled the book, the title still shows up
- I then modified the title to make sure im not seeing a cached version and the page updates accordingly

<img width="1512" alt="Screenshot 2023-05-13 at 11 47 47 AM" src="https://github.com/m2lines/L96_demo/assets/32878682/7a7ac02e-6349-435d-ba22-9ca417fc90f9">

as @shan18 mentioned, deleting cache removed the title for him as well but I did was not able to replicate that. 

For now, more investigation is required

**Comment by IamShubhamGupto** [comment]
spent some more time on it today

My local build from the latest commit
<img width="1512" alt="Screenshot 2023-05-31 at 12 32 29 AM" src="https://github.com/m2lines/L96_demo/assets/32878682/e81e130e-cfd4-4970-8a03-4feb3b403cf7">

I will be raising a pr which changes the way we deploy on GitHub pages, that might be a solution. We won't know until its merged and built

**Comment by IamShubhamGupto** [comment]
@LaureZanna 
With the title back on https://m2lines.github.io/L96_demo/intro.html, should we close this?
