### ISSUE TITLE
Closing page

### ISSUE THREAD

**Issue by LaureZanna** [m2lines/L96_demo#116]
After discussion wtih @dhruvbalwada , one idea is to close the notebook by adding some comments and references from M2LinES' work.

**Comment by dhruvbalwada** [comment]
I have added a notebook https://github.com/m2lines/L96_demo/blob/main/notebooks/closing_remarks.ipynb for the closing remarks. Please add these in when you get a chance @LaureZanna

**Comment by dhruvbalwada** [comment]
The text for this page is being developed here: 
https://docs.google.com/document/d/1QqummfWgQ5NUX5M0DXD1pchTxDneXaCNuLONQL7nscM/edit
