### ISSUE TITLE
Time-scale for climatology based error metric

### ISSUE THREAD

**Issue by NoraLoose** [m2lines/L96_demo#123]
The notebook https://m2lines.github.io/L96_demo/notebooks/gcm-parameterization-problem.html introduces the **Climatology based error metric** (equation 6). The [subsequent figure](https://m2lines.github.io/L96_demo/_images/727464e984e0b908fda68a94fa609cf3232f42b00f07fc1393cafdad4256cf60.png) shows the climatology of the truth vs. unparameterized GCM vs. parameterized GCM; it suggests that the climatology of the parameterized GCM (blue line) is closer to that of the true climatology (black line) than that of the umparameterized GCM (red line).

### Issue

The climatologies were only computed for a time window of t = [0, 100], which is not long enough. Here is a figure that shows the computed climatology as a function of the time window. For short time windows (e.g., t = [0, 100]), the parameterized GCM (blue line) has indeed a time-mean that is closer to the truth. But for longer time scales, the climatology of the unparameterized GCM is better.

![evolution_climatology_X4](https://github.com/m2lines/L96_demo/assets/23617395/b00e34eb-3a1a-4b32-bea4-2cbe1e20ec7d)

I think we have to run the models in that notebook for longer to obtain reliable climatologies.

**Comment by NoraLoose** [comment]
The fact that the parameterized GCM has a larger error in its climatology than the unparameterized GCM seems to be counter-intuitive at first. But it just highlights the fact that the climatology on its own is not the best metric. Here is the distribution of the `X_k` variables, where the samples range over all k and all times up to T = 5000.

![L96_distributions](https://github.com/m2lines/L96_demo/assets/23617395/dd2cc2ae-e93b-49ab-82a4-fea1e97f46ab)

This second figure confirms what we saw in the first figure: the mean (aka climatology) of the unparameterized GCM (green line) matches the mean of the true distribution (blue line) better than the mean of the parameterized GCM (orange line). The higher moments in the green distribution are however completely off.

If we computed the Wasserstein metric between these distributions, we would find that the parameterized GCM has higher skill than the unparameterized GCM. Could consider adding such a distribution metric to the notebook / book?

**Comment by dhruvbalwada** [comment]
Thank you for digging into this Nora. This is definitely a very interesting result. 

Could you make a PR to the notebook (if you have time). I would recommend doing 2 things: 
- Point out that climatology metric has different response at different time scales, and should be used with caution. 
- Discuss and add some PDF based metric. 

It might also be worth discussing and showing how the PDFs evolve in time. Is it just random chance that the climatology metric worked at short time (we had poor estimate of the mean) ?

**Comment by dhruvbalwada** [comment]
It should be fine to increase execution time for this. I think we have some other notebooks that take much longer, so increasing the time about 10-15 times here should not be a problem. 

Also, if you think it is not too hard maybe you can fix the random seed in this notebook, save the data for a longer run (which should not be too large and we can add to the repo), and then open that dataset for this particular metric. This way things can stay fast.

**Comment by NoraLoose** [comment]
Hi @dhruvbalwada, I just submitted a PR that introduces a pdf-based error metric. 

- To get reliable metrics, I changed the integration time to T=1000 (from T=100). The notebook is still faster than others, so this is not a deal-breaker.
- I opted for not showing how the PDFs (nor the climatology) evolve over time because the notebook is already pretty long. Let me know what you think.
