### ISSUE TITLE
Prepare for JOSE submission

### ISSUE THREAD

**Issue by dhruvbalwada** [m2lines/L96_demo#135]
We will submit this repo to JOSE. The submission requirements are detailed [here](https://openjournals.readthedocs.io/en/jose/submitting.html). 

Tasks:
- [x] Check if there is or add an OSI-approved license.
- [x] Add a short markdown paper: `paper.md`.
- [x] Reference for the above markdown should be added to `paper.bib`. 

What should be in `paper.md`: 
- [x] List all authors and affiliations.
- [x] Describe submission and explain eligibility for JOSE.
- [x] Have a statement of need section.
- [x] Describe the functionality or learning objectives.
- [x] Tell story of the project (how it came to be). 
- [x] Cite key papers.
- [x] Should be about 1000 words or 2 pages.

**Comment by dhruvbalwada** [comment]
**Draft**:  
I wrote a first draft of the submission for JOSE: https://github.com/m2lines/L96_demo/blob/neural_net_for_L96/paper.md (I know this can be annoying to edit, so the text can be edited on this [google doc](https://docs.google.com/document/d/1Ajnsi-1B7AuLSzXjgzYnfXl2rr1oioZERd87L55AoEA/edit?usp=sharing))
The main things that need to be covered in a JOSE article are in the list above (I got it from JOSE website). It should be short ~ 1000 words. I based this on the introduction that is part of our jupyter book, but made some minor modifications. Also based on [example](https://joss.theoj.org/papers/10.21105/joss.00388) provided by JOSE. 

**Authors**: 
I included everyone who replied to me about this (https://docs.google.com/spreadsheets/d/14DM7wuhKjexrYV9e9GT0fYKZfW0AvqkrDh0xPQnO3dM/edit#gid=0). However, a few people are left who have not replied. I am assuming they are too busy. Should I individually ping them?

**Comment by LaureZanna** [comment]
@dhruvbalwada : the draft is outstanding!! just made some minor edits.  
For pinging authors: @johannag126 might be able to help you and reach out to them directly so you can move ahead with submission? 

Thanks again @dhruvbalwada for your leadership!

**Comment by dhruvbalwada** [comment]
Submitted https://jose.theoj.org/papers/c644a0264f445698f212a051d8ace6e8
