### ISSUE TITLE
Creating initial release

### ISSUE THREAD

**Issue by dhruvbalwada** [m2lines/L96_demo#155]
@IamShubhamGupto do you know how to solve the first remark that the reviewer made [here](https://github.com/openjournals/jose-reviews/issues/241#issuecomment-2067800371) about creating an initial release?

**Comment by dhruvbalwada** [comment]
In this process can we also delete the branches that have been merged (except the ones we are actively using to address reviewer comments), so that there is a fresh start.

**Comment by IamShubhamGupto** [comment]
Hey @dhruvbalwada, Ive merged the previous PR as I think it address the concerns of the review. For creating a release, Ive started a draft release [here](https://github.com/m2lines/L96_demo/releases). I hope youre able to see it. If not, let me know if you have any preference for the release title and description. Ive provided very basic entries for now. 


You can either edit the draft or share the contents with me and I'll publish the release.

**Comment by dhruvbalwada** [comment]
I think the title and description seem good to me. Do we need to do anything else before we publish? 
Now that the README has also been ingested, maybe it makes sense to publish? 
If we make some changes to read me in response to the reviews, will they automatically appear in the release?

**Comment by IamShubhamGupto** [comment]
> I think the title and description seem good to me. Do we need to do anything else before we publish? Now that the README has also been ingested, maybe it makes sense to publish? If we make some changes to read me in response to the reviews, will they automatically appear in the release?

unfortunately, we would have to manually re release a newer version say `v1.1` to incorporate further changes by the reviewers. Ill create a release now and if further changes are required, we can always bump up the version number

**Comment by dhruvbalwada** [comment]
Sounds good to me. Thank you.
