### ISSUE TITLE
Some minor paper.md edits

### ISSUE THREAD

**Issue by magsol** [m2lines/L96_demo#158]
In performing final review/editing checks I've read through your paper. The basic structure and content flow are great, but there are some grammatical and syntactical inconsistencies that should be corrected before final acceptance and publication. In no particular order:

 - Inconsistency in the use of "ML" versus "machine learning"; since the acronym "ML" is defined in the first sentence, it would stand to reason that any subsequent reference be simply "ML".
 - No need for the "(described later)" parenthetical, as this is the core subject matter of your book.
 - Both "subgrid processes" and "sub-gridd processes" appear; pick one or the other.
 - "i.e." should always have periods after each letter (there's one in the second sentence that does not).
 - There's a missing Oxford comma in the second sentence of the second paragraph ("to simulate, understand and predict climate"); everywhere else, the Oxford comma is used, hence consistency would dictate using it here too.

**Comment by magsol** [comment]
I think there is also a missing reference: I see `@christensen2022parametrization` in the text but only `@Lorenz1995` appears in the bib file. See https://github.com/openjournals/jose-reviews/issues/241#issuecomment-2292175030

**Comment by dhruvbalwada** [comment]
Thank you for these comments, I have resolved all these issues now.
