### ISSUE TITLE
Create a notebook about L96 itself and its implementation

### ISSUE THREAD

**Issue by rabernat** [m2lines/L96_demo#24]
The L96 model currently lives in a standalone module (see #22). But the book (#15) does not have any explanation or text about this.

We need a notebook that simply describes the L96 system and shows how it's coded. This can probably be adapted from the slides.

**Comment by bhouri0412** [comment]
I am working on this issue. I will make a pull request once I finished creating the notebook.

**Comment by bhouri0412** [comment]
I just created a pull request to solve this issue. Please let me know if there is any suggestion to improve the notebook.

**Comment by bhouri0412** [comment]
I forgot to mention, but I also changed the text between the codes and at the end to explain what each block of code is performing. It would be great if someone could review those changes too!
