### ISSUE TITLE
WARNING: Non-consecutive header level increase

### ISSUE THREAD

**Issue by rabernat** [m2lines/L96_demo#38]
These warnings appear frequently when building the book. Markdown headings need to be used consistently, e.g.

```
# Title

## Heading 1

### Heading 2
```

etc. 

We need to go through the notebooks and fix all of these issues so that the warnings go away.

**Comment by rabernat** [comment]
Also related are these issues

```
home/runner/work/L96_demo/L96_demo/intro.md:1: WARNING: toctree contains reference to document 'notebooks/L96-description' that doesn't have a title: no link will be generated
/home/runner/work/L96_demo/L96_demo/intro.md:1: WARNING: toctree contains reference to document 'notebooks/gcm-analog-demo' that doesn't have a title: no link will be generated
...
```

etc.

**Comment by breichl** [comment]
This issue has been fixed in a couple of notebooks, but issues remain in the following:
- estimating-gcm-parameters.ipynb
- random_forest_parameterization.ipynb
- README.md.

**Comment by IamShubhamGupto** [comment]
#87 should fix this warning in the `random_forest_parameterization.ipynb` notebook

**Comment by dhruvbalwada** [comment]
@shan18 and @IamShubhamGupto - should this be closed now?

**Comment by shan18** [comment]
Yes, it can be closed now. These issues have been fixed.
