### ISSUE TITLE
Equations are not always formatted properly

### ISSUE THREAD

**Issue by rabernat** [m2lines/L96_demo#45]
We need to figure out why and fix it.

Example: https://m2lines.github.io/L96_demo/notebooks/presentation-model-setup.html

<img width="817" alt="image" src="https://user-images.githubusercontent.com/1197350/168888279-8f908247-5d60-4643-b763-cbb321240052.png">

**Comment by breichl** [comment]
It looks like this can be fixed by adding the "dollarmath" extension into the _config.yml file.  I will follow with a commit including this addition.

**Comment by breichl** [comment]
PR #48 fixes this issue in many notebooks, but (for example) there are still some equation issues in Neural_network_for_Lorenz96.ipynb.  That specific issue might be linked to the headers issue #38

**Comment by breichl** [comment]
This issue was solved with PR #48, other issues are separate.
