### ISSUE TITLE
Generation of weights needs to happen first

### ISSUE THREAD

**Issue by rabernat** [m2lines/L96_demo#47]
The notebook `Neural_network_for_Lorenz96.ipynb` generates the file `network_3_layers_100_epoches.pth`, which is used by two downstream notebooks:
- `random_forest_parameterization.ipynb`
- `LRP-L96.ipynb`

Ideally we would make these notebooks execute _after_ `Neural_network_for_Lorenz96.ipynb`. In order to do that, we would need to control the execution order within jupyter book.

**Comment by adcroft** [comment]
#73 solved this problem
