### ISSUE TITLE
Combine notebooks on L96 model

### ISSUE THREAD

**Issue by LaureZanna** [m2lines/L96_demo#50]
These 3 notebooks 

- L96-description
- L96-two-timescale-description 
- presentation-model-setup 

can be merged : one that describes the model equation and expand on why we are using the model ; and another one on how we solve the equations/numerics etc

**Comment by rabernat** [comment]
:+1: to this plan

**Comment by LaureZanna** [comment]
So now we have only 2 notebooks: 
- L96-two-timescale-description: this describes the L96 equations 
- presentation-model-setup: this presents the model and the analogs for our problem 

L96-description is not needed anymore

**Comment by rabernat** [comment]
Right now the titles are showing up as

- L96 analogs for this project: the real world and the GCM with parameterization
- L96 two-timescale model description

I feel like these are note very descriptive. It would be great if we could tell from the titles what they are more specifically.

**Comment by adcroft** [comment]
There is one notebook left over from the clean up, `L96-description`, which really is about single time-scale class the numerical methods available. I think this could be moved to an appendix, and if we don't want an appendix then I'll cut-n-paste just a few snippets to the gcm-analog notebook, and discard the numerics.

**Comment by LaureZanna** [comment]
Up to you. I would be tempted to keep it in an appendix for simplicity.

**Comment by dhruvbalwada** [comment]
I think this is solved now.
