### ISSUE TITLE
Logical issues with estimating-gcm-parameters

### ISSUE THREAD

**Issue by yaniyuval** [m2lines/L96_demo#72]
@lesommer - The nice notebook have several issues that should be fixed before the book is out:
 When you learn the parameters you rely on a single sample. This is true both for learning from the instantaneous differences and the trajectory learning. Furthermore, It would be great if you could learn from many samples, and verify if the result of the new parameters outperforms the prior parameterization for new initial condition (at the moment the test is done on the training data).

**Comment by LaureZanna** [comment]
@shan18 @IamShubhamGupto @dhruvbalwada : did we take care of this in our review?
