### ISSUE TITLE
Split Neural network for L96

### ISSUE THREAD

**Issue by dhruvbalwada** [m2lines/L96_demo#98]
The neural network for L96 notebook is too long and should be split up. I see 3 discrete parts:
- This notebook should focus on the simplest problem. What is section 1 (using NN for L96 parameterization). 
- There should be a separate notebook for non-local problems/deeper networks.
- The remaining stuff (regularization, overfitting, choosing LR etc) could be put in a notebook called "advanced topics in NN training" or something similar.

**Comment by dhruvbalwada** [comment]
At the moment the section: https://m2lines.github.io/L96_demo/notebooks/Neural_network_for_Lorenz96.html#building-neural-networks-in-pytorch seems to be very similar (in principle) to the Introduction to ML notebook. 
@shan18 and @IamShubhamGupto - please discuss on how to consolidate these two, without losing any information. Ideally, this section should be completely contained in Intro to ML, and Using NN for L96 parameterization should be the next step.

**Comment by LaureZanna** [comment]
@dhruvbalwada : good points
